import { useMemo } from "react";
import { AlertTriangle, CalendarPlus, MapPinPlus, Plus, Store, X } from "lucide-react";
import { LocationCombobox } from "@/components/LocationCombobox";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DateTimeField } from "@/components/ui/datetime";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { formatMinutes, splitCount, splitWindow } from "@/lib/pickup";
import { cn } from "@/lib/utils";
import {
  SPLIT_INTERVALS,
  type CampusLocation,
  type OrderType,
  type SlotMode,
  type SplitInterval,
} from "@/types/database";

// ===========================================================================
// Draft shapes
// ===========================================================================
//
// The form edits one tree: spot -> dates -> (optionally) bookable slots.
// It replaces four disconnected fields that used to sit side by side on the
// listing form - "Pickup spots", "Pickup details", "Hours per day" and
// "Pickup days" - and which between them could describe the same pickup three
// different ways, in two places, one of them free text. A club with one table
// running Tue 11-2 and Thu 5-8 now says exactly that, twice, in one place.

/** One bookable piece of a window: a time range and how many may take it. */
export interface SlotPieceDraft {
  /** Set when this slot already exists in the database. */
  id?: string;
  startMinutes: number;
  endMinutes: number;
  max: string;
  /** Reservations already made. A slot with any is never silently removed. */
  reserved: number;
  /** Generated by an auto-split and shorter than the chosen interval. */
  remainder?: boolean;
}

/** One pickup date at one spot. */
export interface WindowDraft {
  id?: string;
  /** YYYY-MM-DD, local. */
  date: string;
  startMinutes: number;
  endMinutes: number;
  slotMode: SlotMode;
  /** 'capacity' mode: total people across the window. */
  capacity: string;
  /** 'split' mode: the interval an auto-split used, or null if hand-built. */
  splitMinutes: SplitInterval | null;
  /** 'split' mode: the slots students book. */
  slots: SlotPieceDraft[];
  note: string;
}

export interface SpotDraft {
  id?: string;
  locationId: string;
  orderType: OrderType;
  windows: WindowDraft[];
  /** Same-day units to carry to THIS table, by item name. */
  sameDay: Record<string, string>;
}

export const MAX_SPOTS = 12;
export const MAX_WINDOWS_PER_SPOT = 14;
/** Auto-split can multiply fast; this is the ceiling across a whole listing. */
export const MAX_SLOTS_PER_LISTING = 240;

const SLOT_MODE_LABEL: Record<SlotMode, string> = {
  open: "Open — anyone can come during this window",
  capacity: "Limited — a set number of people for the whole window",
  split: "Timed slots — students book a specific time",
};

// ===========================================================================
// Helpers
// ===========================================================================

/** "HH:MM" for an <input type="time"> from minutes past midnight. */
function toTimeValue(minutes: number): string {
  const pad = (value: number) => String(value).padStart(2, "0");
  return `${pad(Math.floor(minutes / 60))}:${pad(minutes % 60)}`;
}

function fromTimeValue(value: string): number {
  const [hours, minutes] = value.split(":").map(Number);
  if (!Number.isFinite(hours)) return 0;
  return hours * 60 + (Number.isFinite(minutes) ? minutes : 0);
}

export function emptyWindow(date: string): WindowDraft {
  return {
    date,
    startMinutes: 11 * 60,
    endMinutes: 14 * 60,
    slotMode: "open",
    capacity: "",
    splitMinutes: null,
    slots: [],
    note: "",
  };
}

export function emptySpot(): SpotDraft {
  return { locationId: "", orderType: "preorder", windows: [], sameDay: {} };
}

/** Every slot the whole listing would create, for the ceiling check. */
export function totalSlots(spots: SpotDraft[]): number {
  return spots.reduce(
    (sum, spot) =>
      sum +
      spot.windows.reduce(
        (windowSum, window) =>
          windowSum +
          (window.slotMode === "capacity" ? 1 : window.slotMode === "split" ? window.slots.length : 0),
        0,
      ),
    0,
  );
}

/**
 * Everything wrong with the pickup section, as one message, or undefined.
 * Kept here rather than in the page so the rules and the fields that enforce
 * them cannot drift apart.
 */
export function pickupError(spots: SpotDraft[]): string | undefined {
  const picked = spots.map((spot) => spot.locationId).filter(Boolean);
  if (new Set(picked).size !== picked.length) {
    return "Each pickup spot must be a different campus location.";
  }
  if (spots.some((spot) => !spot.locationId)) {
    return "Pick a campus location for every pickup spot, or remove the empty one.";
  }
  for (const spot of spots) {
    for (const window of spot.windows) {
      if (!window.date) return "Give every pickup date a day.";
      if (window.endMinutes <= window.startMinutes) {
        return "Each pickup window has to end after it starts.";
      }
      if (window.slotMode === "capacity") {
        const capacity = Number.parseInt(window.capacity, 10);
        if (!Number.isFinite(capacity) || capacity < 1) {
          return "Enter how many people can come to each limited window.";
        }
      }
      if (window.slotMode === "split") {
        if (window.slots.length === 0) {
          return "Split a timed window into slots, or switch it back to open.";
        }
        for (const slot of window.slots) {
          const max = Number.parseInt(slot.max, 10);
          if (!Number.isFinite(max) || max < 1) return "Give every time slot a number of spots.";
          if (max < slot.reserved) {
            return `A slot already has ${slot.reserved} reservations. Its number of spots cannot go below that.`;
          }
        }
      }
    }
  }
  if (totalSlots(spots) > MAX_SLOTS_PER_LISTING) {
    return `That is more than ${MAX_SLOTS_PER_LISTING} bookable slots on one drop. Use longer slots or fewer dates.`;
  }
  return undefined;
}

// ===========================================================================
// One window
// ===========================================================================

function WindowRow({
  window,
  index,
  spotIndex,
  onChange,
  onRemove,
}: {
  window: WindowDraft;
  index: number;
  spotIndex: number;
  onChange: (patch: Partial<WindowDraft>) => void;
  onRemove: () => void;
}) {
  const fieldId = `spot-${spotIndex}-window-${index}`;
  const invalidRange = window.endMinutes <= window.startMinutes;
  const remainder = window.slots.find((slot) => slot.remainder);
  const reservedTotal = window.slots.reduce((sum, slot) => sum + slot.reserved, 0);

  const applySplit = (interval: SplitInterval) => {
    const pieces = splitWindow(window.startMinutes, window.endMinutes, interval);
    onChange({
      slotMode: "split",
      splitMinutes: interval,
      // Carry existing reservations onto any regenerated slot covering the
      // same start time, so re-splitting a window never quietly drops a
      // student's booking. Slots that no longer line up keep their old row
      // until the club removes them, and the form blocks removing a booked one.
      slots: pieces.map((piece) => {
        const existing = window.slots.find((slot) => slot.startMinutes === piece.startMinutes);
        return {
          id: existing?.id,
          startMinutes: piece.startMinutes,
          endMinutes: piece.endMinutes,
          max: existing?.max ?? "10",
          reserved: existing?.reserved ?? 0,
          remainder: piece.remainder,
        };
      }),
    });
  };

  const addManualSlot = () => {
    const last = window.slots[window.slots.length - 1];
    const start = last ? last.endMinutes : window.startMinutes;
    onChange({
      splitMinutes: null,
      slots: [
        ...window.slots,
        {
          startMinutes: start,
          endMinutes: Math.min(start + 30, window.endMinutes),
          max: "10",
          reserved: 0,
        },
      ],
    });
  };

  const updateSlot = (slotIndex: number, patch: Partial<SlotPieceDraft>) => {
    onChange({
      // Any hand edit means the split is no longer purely "every N minutes".
      splitMinutes: null,
      slots: window.slots.map((slot, i) => (i === slotIndex ? { ...slot, ...patch } : slot)),
    });
  };

  return (
    <div className="rounded-xl border border-border/70 bg-surface p-3">
      <div className="flex flex-wrap items-end gap-2">
        <div className="min-w-0 flex-1 basis-full sm:basis-40">
          <Label htmlFor={`${fieldId}-date`} className="mb-1 text-xs">
            Date
          </Label>
          <DateTimeField
            id={`${fieldId}-date`}
            type="date"
            value={window.date}
            onChange={(e) => onChange({ date: e.target.value })}
          />
        </div>
        <div className="min-w-0 flex-1 basis-[calc(50%-0.25rem)] sm:basis-32">
          <Label htmlFor={`${fieldId}-from`} className="mb-1 text-xs">
            From
          </Label>
          <DateTimeField
            id={`${fieldId}-from`}
            type="time"
            value={toTimeValue(window.startMinutes)}
            onChange={(e) => onChange({ startMinutes: fromTimeValue(e.target.value) })}
          />
        </div>
        <div className="min-w-0 flex-1 basis-[calc(50%-0.25rem)] sm:basis-32">
          <Label htmlFor={`${fieldId}-to`} className="mb-1 text-xs">
            To
          </Label>
          <DateTimeField
            id={`${fieldId}-to`}
            type="time"
            invalid={invalidRange}
            value={toTimeValue(window.endMinutes)}
            onChange={(e) => onChange({ endMinutes: fromTimeValue(e.target.value) })}
          />
        </div>
        {reservedTotal > 0 ? (
          <Badge variant="default" className="mb-1.5">
            {reservedTotal} booked
          </Badge>
        ) : (
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={onRemove}
            aria-label={`Remove pickup date ${index + 1}`}
            className="mb-0.5 px-2.5 text-ink-muted"
          >
            <X className="size-4" aria-hidden="true" />
          </Button>
        )}
      </div>

      {invalidRange && (
        <p className="mt-1.5 text-xs font-medium text-accent" role="alert">
          The end time has to be after the start time.
        </p>
      )}

      <div className="mt-2.5">
        <Label htmlFor={`${fieldId}-mode`} className="mb-1 text-xs">
          Who can come
        </Label>
        <Select
          id={`${fieldId}-mode`}
          value={window.slotMode}
          onChange={(e) => {
            const slotMode = e.target.value as SlotMode;
            onChange({
              slotMode,
              slots: slotMode === "split" ? window.slots : [],
              splitMinutes: slotMode === "split" ? window.splitMinutes : null,
            });
          }}
        >
          {(Object.keys(SLOT_MODE_LABEL) as SlotMode[]).map((mode) => (
            <option key={mode} value={mode}>
              {SLOT_MODE_LABEL[mode]}
            </option>
          ))}
        </Select>
      </div>

      {window.slotMode === "open" && (
        <p className="mt-1.5 text-[11px] text-ink-muted">
          Students see this window on the listing and can add it to their calendar. Nothing to
          book, and no one is turned away.
        </p>
      )}

      {window.slotMode === "capacity" && (
        <div className="mt-2 flex flex-wrap items-center gap-2">
          <Input
            value={window.capacity}
            onChange={(e) => onChange({ capacity: e.target.value.replace(/[^\d]/g, "") })}
            inputMode="numeric"
            placeholder="40"
            aria-label="People who can book this window"
            className="w-24 font-mono"
          />
          <span className="text-sm text-ink-muted">people across the whole window</span>
        </div>
      )}

      {window.slotMode === "split" && (
        <div className="mt-2.5 space-y-2">
          <div className="flex flex-wrap items-center gap-1.5">
            <span className="text-xs font-semibold text-ink-muted">Split into</span>
            {SPLIT_INTERVALS.map((interval) => (
              <Button
                key={interval}
                type="button"
                size="sm"
                variant={window.splitMinutes === interval ? "primary" : "secondary"}
                disabled={invalidRange}
                onClick={() => applySplit(interval)}
              >
                {interval} min
              </Button>
            ))}
            <Button type="button" size="sm" variant="ghost" onClick={addManualSlot}>
              <Plus className="size-4" aria-hidden="true" />
              Add one by hand
            </Button>
          </div>

          {window.splitMinutes && !invalidRange && window.slots.length === 0 && (
            <p className="text-[11px] text-ink-muted">
              This window would become {splitCount(window.startMinutes, window.endMinutes, window.splitMinutes)}{" "}
              slots.
            </p>
          )}

          {remainder && (
            <p className="flex items-start gap-1.5 rounded-lg bg-primary/15 p-2 text-[11px] text-ink">
              <AlertTriangle className="mt-px size-3.5 shrink-0" aria-hidden="true" />
              <span>
                The last slot is short ({formatMinutes(remainder.startMinutes)} to{" "}
                {formatMinutes(remainder.endMinutes)}) because the window does not divide evenly.
                Keep it, remove it, or change the end time.
              </span>
            </p>
          )}

          {window.slots.map((slot, slotIndex) => (
            <div
              key={slot.id ?? `${slot.startMinutes}-${slotIndex}`}
              className={cn(
                "flex flex-wrap items-center gap-2 rounded-lg border border-border/60 px-2.5 py-2",
                slot.remainder && "border-primary-dark/40 bg-primary/5",
              )}
            >
              <DateTimeField
                type="time"
                value={toTimeValue(slot.startMinutes)}
                onChange={(e) => updateSlot(slotIndex, { startMinutes: fromTimeValue(e.target.value) })}
                aria-label={`Slot ${slotIndex + 1} start`}
                className="h-9 w-32 text-sm"
              />
              <span className="text-xs text-ink-muted">to</span>
              <DateTimeField
                type="time"
                value={toTimeValue(slot.endMinutes)}
                onChange={(e) => updateSlot(slotIndex, { endMinutes: fromTimeValue(e.target.value) })}
                aria-label={`Slot ${slotIndex + 1} end`}
                className="h-9 w-32 text-sm"
              />
              <Input
                value={slot.max}
                onChange={(e) => updateSlot(slotIndex, { max: e.target.value.replace(/[^\d]/g, "") })}
                inputMode="numeric"
                aria-label={`Spots in slot ${slotIndex + 1}`}
                className="h-9 w-20 font-mono text-sm"
              />
              <span className="text-xs text-ink-muted">spots</span>
              {slot.reserved > 0 ? (
                <Badge variant="default">{slot.reserved} booked</Badge>
              ) : (
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  className="ml-auto px-2 text-ink-muted"
                  aria-label={`Remove slot ${slotIndex + 1}`}
                  onClick={() =>
                    onChange({
                      splitMinutes: null,
                      slots: window.slots.filter((_, i) => i !== slotIndex),
                    })
                  }
                >
                  <X className="size-4" aria-hidden="true" />
                </Button>
              )}
            </div>
          ))}
        </div>
      )}

      <div className="mt-2">
        <Input
          value={window.note}
          onChange={(e) => onChange({ note: e.target.value })}
          placeholder="Anything students should know about this day (optional)"
          aria-label={`Note for pickup date ${index + 1}`}
          maxLength={160}
          className="h-9 text-sm"
        />
      </div>
    </div>
  );
}

// ===========================================================================
// One spot: where, what ordering, its dates, and its same-day pile
// ===========================================================================

function SpotCard({
  spot,
  index,
  locations,
  itemNames,
  sameDayEnabled,
  defaultDate,
  onChange,
  onRemove,
}: {
  spot: SpotDraft;
  index: number;
  locations: CampusLocation[];
  itemNames: string[];
  sameDayEnabled: boolean;
  defaultDate: string;
  onChange: (patch: Partial<SpotDraft>) => void;
  onRemove: () => void;
}) {
  const takesWalkUps = spot.orderType === "same_day" || spot.orderType === "both";
  const bookedHere = spot.windows.some((window) =>
    window.slots.some((slot) => slot.reserved > 0),
  );

  return (
    <div className="rounded-2xl border border-border bg-surface-raised p-3">
      <div className="flex flex-wrap items-end gap-2">
        <div className="min-w-0 flex-1 basis-full sm:basis-52">
          <Label htmlFor={`spot-location-${index}`} className="mb-1 text-xs">
            Campus spot
          </Label>
          <LocationCombobox
            id={`spot-location-${index}`}
            locationId={spot.locationId}
            locations={locations}
            onChange={(locationId) => onChange({ locationId })}
            emptyHint="Not listed? Add your own spot below."
          />
        </div>
        <div className="min-w-0 flex-1 basis-full sm:basis-44">
          <Label htmlFor={`spot-type-${index}`} className="mb-1 text-xs">
            Ordering here
          </Label>
          <Select
            id={`spot-type-${index}`}
            value={spot.orderType}
            onChange={(e) => onChange({ orderType: e.target.value as OrderType })}
          >
            <option value="preorder">Pre-order only</option>
            <option value="same_day">Same-day pickup</option>
            <option value="both">Pre-order &amp; same-day</option>
          </Select>
        </div>
        {bookedHere ? (
          <Badge variant="default" className="mb-1.5">
            Has bookings
          </Badge>
        ) : (
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={onRemove}
            aria-label={`Remove pickup spot ${index + 1}`}
            className="mb-0.5 px-2.5 text-ink-muted"
          >
            <X className="size-4" aria-hidden="true" />
          </Button>
        )}
      </div>

      <div className="mt-3">
        <p className="mb-1.5 text-xs font-bold uppercase tracking-wide text-ink-muted">
          Pickup dates and times
        </p>
        {spot.windows.length === 0 ? (
          <p className="text-xs text-ink-muted">
            No dates yet. Add one per day you are at this spot; the same spot can run on as many
            days as you like, at different times.
          </p>
        ) : (
          <div className="space-y-2">
            {spot.windows.map((window, windowIndex) => (
              <WindowRow
                key={window.id ?? `${window.date}-${windowIndex}`}
                window={window}
                index={windowIndex}
                spotIndex={index}
                onChange={(patch) =>
                  onChange({
                    windows: spot.windows.map((w, i) => (i === windowIndex ? { ...w, ...patch } : w)),
                  })
                }
                onRemove={() =>
                  onChange({ windows: spot.windows.filter((_, i) => i !== windowIndex) })
                }
              />
            ))}
          </div>
        )}
        <Button
          type="button"
          variant="secondary"
          size="sm"
          className="mt-2"
          disabled={spot.windows.length >= MAX_WINDOWS_PER_SPOT}
          onClick={() =>
            onChange({
              windows: [
                ...spot.windows,
                // A new date copies the last one's times: a club adding
                // Tuesday and Thursday almost always runs the same hours.
                spot.windows.length > 0
                  ? { ...emptyWindow(defaultDate), startMinutes: spot.windows[spot.windows.length - 1].startMinutes, endMinutes: spot.windows[spot.windows.length - 1].endMinutes }
                  : emptyWindow(defaultDate),
              ],
            })
          }
        >
          <CalendarPlus className="size-4" aria-hidden="true" />
          Add a pickup date
        </Button>
      </div>

      {/* Once the drop sells at the table, this block is ALWAYS rendered on
          every spot. It used to appear only when the spot already took
          walk-ups and items already existed, which meant a club that turned
          the feature on and looked at a pre-order spot saw nothing at all and
          had no way to find out why. Each dead end now says what it is and
          offers the one control that fixes it. */}
      {sameDayEnabled && (
        <div className="mt-3 rounded-xl border border-border/70 bg-surface p-3">
          <p className="text-xs font-bold uppercase tracking-wide text-ink-muted">
            Same-day stock at this spot
          </p>

          {!takesWalkUps ? (
            <>
              <p className="mt-1 text-[11px] text-ink-muted">
                This spot is pre-order only, so nothing is sold here on the day. Let it take
                walk-ups and the counts appear.
              </p>
              <Button
                type="button"
                variant="secondary"
                size="sm"
                className="mt-2"
                onClick={() => onChange({ orderType: "both" })}
              >
                <Store className="size-4" aria-hidden="true" />
                Take walk-ups here too
              </Button>
            </>
          ) : itemNames.length === 0 ? (
            <p className="mt-1 text-[11px] text-ink-muted">
              Add an item with a name under "Items, prices, dietary tags" above, and a box for it
              appears here.
            </p>
          ) : (
            <>
              <p className="mt-1 text-[11px] text-ink-muted">
                How many you are carrying here to sell on the day. Separate from pre-order limits,
                and you can change it from your Orders page while the table is running.
              </p>
              <div className="mt-2 grid gap-2 sm:grid-cols-2">
                {itemNames.map((name) => (
                  <label key={name} className="flex items-center gap-2">
                    <Input
                      value={spot.sameDay[name] ?? ""}
                      onChange={(e) =>
                        onChange({
                          sameDay: { ...spot.sameDay, [name]: e.target.value.replace(/[^\d]/g, "") },
                        })
                      }
                      inputMode="numeric"
                      placeholder="0"
                      aria-label={`Same-day units of ${name} at spot ${index + 1}`}
                      className="h-9 w-20 font-mono text-sm"
                    />
                    <span className="min-w-0 truncate text-sm">{name}</span>
                  </label>
                ))}
              </div>
              <p className="mt-1.5 text-[11px] text-ink-muted">
                Leave a box blank or at 0 for anything you are not selling at this table.
              </p>
            </>
          )}
        </div>
      )}
    </div>
  );
}

// ===========================================================================
// The section
// ===========================================================================

export function PickupEditor({
  spots,
  locations,
  itemNames,
  sameDayEnabled,
  defaultDate,
  onChange,
}: {
  spots: SpotDraft[];
  locations: CampusLocation[];
  /** Item names from the items editor, for the same-day counts. */
  itemNames: string[];
  sameDayEnabled: boolean;
  /** Seed date for a newly added window (usually the drop's end date). */
  defaultDate: string;
  onChange: (spots: SpotDraft[]) => void;
}) {
  const slotCount = useMemo(() => totalSlots(spots), [spots]);

  return (
    <div className="space-y-2.5">
      {spots.length === 0 && (
        <p className="text-xs text-ink-muted">
          Add the places students collect from. Each spot carries its own dates and times, so one
          table can run on several days, and several tables can run on the same day.
        </p>
      )}

      {spots.map((spot, index) => (
        <SpotCard
          key={spot.id ?? `new-${index}`}
          spot={spot}
          index={index}
          locations={locations}
          itemNames={itemNames}
          sameDayEnabled={sameDayEnabled}
          defaultDate={defaultDate}
          onChange={(patch) => onChange(spots.map((s, i) => (i === index ? { ...s, ...patch } : s)))}
          onRemove={() => onChange(spots.filter((_, i) => i !== index))}
        />
      ))}

      <div className="flex flex-wrap items-center gap-2">
        <Button
          type="button"
          variant="secondary"
          size="sm"
          disabled={spots.length >= MAX_SPOTS}
          onClick={() => onChange([...spots, emptySpot()])}
        >
          <MapPinPlus className="size-4" aria-hidden="true" />
          Add pickup spot
        </Button>
        {slotCount > 0 && (
          <span
            className={cn(
              "text-xs text-ink-muted",
              slotCount > MAX_SLOTS_PER_LISTING && "font-semibold text-accent",
            )}
          >
            {slotCount} bookable {slotCount === 1 ? "slot" : "slots"} on this drop
            {slotCount > MAX_SLOTS_PER_LISTING ? ` (max ${MAX_SLOTS_PER_LISTING})` : ""}
          </span>
        )}
      </div>
    </div>
  );
}
